[package]
name = "extractor"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common"}
db = { path = "../db" }
actix-web = { workspace = true }
futures = { workspace = true }
sqlx = { workspace = true }
log = { workspace = true }
