[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common"}
chrono = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
url = { workspace = true }